[Database]
Driver = "sqlite"
Name = "pnp-zone.sqlite3"
Host = "localhost"
Port = 3006
User = "pnp-zone"
Password = ""

[Server]
ListenAddress = "127.0.0.1:8000"
AllowedHosts = [
    {Host = "127.0.0.1:8000", Https = false},
]
UseForwardedProtoHeader = true
TemplatePath = "templates/"
StaticPath = "static/"
PluginPath = "plugins/"