# Generated by Django 3.2 on 2022-01-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='campaign.campaignmodel'),
        ),
        migrations.AddField(
            model_name='image',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.room'),
        ),
        migrations.AddField(
            model_name='character',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.room'),
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('room', 'identifier')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('room', 'identifier')},
        ),
    ]
