# Generated by Django 3.1.5 on 2021-01-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default='red', max_length=255),
            preserve_default=False,
        ),
    ]
