# Generated by Django 3.2 on 2022-01-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='name',
            field=models.CharField(blank=True, default='Unnamed layer', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.characterlayer'),
        ),
        migrations.AlterField(
            model_name='image',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.imagelayer'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.tilelayer'),
        ),
    ]
