# Generated by Django 3.2 on 2022-01-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together={('room', 'x', 'y')},
        ),
    ]
