# Generated by Django 3.1.5 on 2021-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210111_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='y',
            field=models.FloatField(),
        ),
    ]
