# Generated by Django 3.2 on 2022-01-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20220128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='board_scale',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='board_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='board_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
