# Generated by Django 3.1.5 on 2021-01-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210119_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='snap',
            field=models.BooleanField(default=True),
        ),
    ]
