# Generated by Django 3.2 on 2022-01-19 20:18

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220119_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='identifier',
            field=models.CharField(blank=True, default=board.models.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(blank=True, default=board.models.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='identifier',
            field=models.CharField(blank=True, default=board.models.uuid4, max_length=255, unique=True),
        ),
    ]
