# Generated by Django 3.2 on 2022-02-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220205_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='replacing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.room'),
        ),
    ]
