# Generated by Django 3.1.5 on 2021-01-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_character_snap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='snap',
        ),
        migrations.AlterField(
            model_name='character',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='y',
            field=models.IntegerField(),
        ),
    ]
