# Generated by Django 3.2 on 2022-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20220119_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
