# Generated by Django 3.1.5 on 2021-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_room_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.PositiveIntegerField(default=32),
            preserve_default=False,
        ),
    ]
