# Generated by Django 3.1.6 on 2021-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='background',
            field=models.CharField(blank=True, default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='field',
            name='border',
            field=models.CharField(blank=True, default='black', max_length=255),
        ),
    ]
