# Generated by Django 3.1.6 on 2021-02-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20210207_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='Tile',
        ),
    ]
