# Generated by Django 3.1.6 on 2021-02-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20210208_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='width',
        ),
        migrations.AddField(
            model_name='room',
            name='defaultBackground',
            field=models.CharField(default='white', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='defaultBorder',
            field=models.CharField(default='black', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
