# Generated by Django 3.1.6 on 2021-02-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20210220_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='background',
            new_name='backgroundImage',
        ),
    ]
