# Generated by Django 3.1.6 on 2021-02-21 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0013_auto_20210221_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='moderators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
