# Generated by Django 3.1.6 on 2021-03-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='backgroundImage',
        ),
    ]
