# Generated by Django 3.2 on 2021-07-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_room_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default='#FF0000', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='identifier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
