# Generated by Django 3.2 on 2021-07-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_auto_20210707_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('layer', models.CharField(choices=[('T', 'Top'), ('M', 'Middle'), ('B', 'Bottom')], default='B', max_length=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.room')),
            ],
            options={
                'unique_together': {('room', 'identifier')},
            },
        ),
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
