# Generated by Django 3.2 on 2022-01-18 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_auto_20210707_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='identifier',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
