# Generated by Django 3.2 on 2021-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_remove_room_moderators'),
        ('campaign', '0002_campaignmodel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmodel',
            name='room',
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='room',
            field=models.ManyToManyField(blank=True, to='board.Room'),
        ),
    ]
