# Generated by Django 3.2 on 2021-07-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20210420_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactermodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
