# Generated by Django 3.2 on 2021-10-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_auto_20210707_2123'),
        ('campaign', '0004_charactermodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='lobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.room'),
            preserve_default=False,
        ),
    ]
