# Generated by Django 3.2 on 2022-01-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_room_campaign'),
        ('campaign', '0005_campaignmodel_lobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmodel',
            name='room',
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='board.room'),
        ),
    ]
