# Generated by Django 3.2 on 2021-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
