# Generated by Django 3.1.2 on 2020-10-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0031_auto_20201013_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('trial', models.CharField(default='', max_length=255)),
                ('effect', models.TextField(default='')),
                ('casting_time', models.CharField(default='', max_length=255)),
                ('casting_cost', models.CharField(default='', max_length=255)),
                ('range', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('target_category', models.CharField(default='', max_length=255)),
                ('leveling_cost', models.CharField(default='', max_length=255)),
                ('aspect', models.ManyToManyField(to='character.GodAspectModel')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CeremonyExtensionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceremonies.ceremonymodel')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel')),
            ],
        ),
    ]
