# Generated by Django 3.1.2 on 2020-10-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceremonies', '0003_auto_20201015_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremonymodel',
            name='trial_modifier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
