# Generated by Django 3.1.2 on 2020-10-19 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0038_levelingcostmodel'),
        ('ceremonies', '0004_ceremonymodel_trial_modifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonymodel',
            name='leveling_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.levelingcostmodel'),
        ),
    ]
