# Generated by Django 3.1.2 on 2020-10-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0039_auto_20201019_0729'),
        ('ceremonies', '0005_auto_20201019_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonymodel',
            name='leveling_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.levelingcostmodel'),
        ),
    ]
