# Generated by Django 3.1.5 on 2021-01-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0041_auto_20201021_1058'),
        ('wiki', '0002_ceremonyextensionmodel_ceremonymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlessingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('effect', models.TextField()),
                ('range', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('target_category', models.CharField(default='', max_length=255)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel')),
            ],
        ),
    ]
