# Generated by Django 3.1.2 on 2020-10-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
                ('adventurer_point_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CultureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DisadvantageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=1024)),
                ('adventurer_point_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpellModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trial', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=255)),
                ('casting_time', models.CharField(max_length=255)),
                ('casting_cost', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('target_category', models.CharField(max_length=255)),
                ('aspect', models.CharField(max_length=255)),
                ('spread', models.CharField(max_length=255)),
                ('leveling_cost', models.CharField(max_length=1)),
                ('rule_book', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='birth_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='birth_place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='characteristics',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='family',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='hair_color',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='other',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SpellExtensionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_skill_value', models.IntegerField()),
                ('adventurer_point_cost', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('_spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.spellmodel')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('health_base', models.IntegerField()),
                ('soul_resistance_base', models.IntegerField()),
                ('body_resistance_base', models.IntegerField()),
                ('speed_base', models.IntegerField()),
                ('ability_max_modifier', models.CharField(default='', max_length=255)),
                ('adventurer_point_cost', models.IntegerField()),
                ('advantages', models.ManyToManyField(to='character.AdvantageModel')),
                ('disadvantages', models.ManyToManyField(to='character.DisadvantageModel')),
            ],
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='culture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='character.culturemodel'),
        ),
        migrations.AddField(
            model_name='charactermodel',
            name='species',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='character.speciesmodel'),
        ),
    ]
