# Generated by Django 3.1.2 on 2020-10-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20201006_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesmodel',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='character.AdvantageModel'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='disadvantages',
            field=models.ManyToManyField(blank=True, to='character.DisadvantageModel'),
        ),
    ]
