# Generated by Django 3.1.2 on 2020-10-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20201006_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='characteristics',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='culture',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='character.culturemodel'),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='family',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='hair_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='other',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='species',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='character.speciesmodel'),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
