# Generated by Django 3.1.2 on 2020-10-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_auto_20201006_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodel',
            name='culture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.culturemodel'),
        ),
        migrations.AlterField(
            model_name='charactermodel',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.speciesmodel'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='advantages',
            field=models.ManyToManyField(null=True, to='character.AdvantageModel'),
        ),
        migrations.AlterField(
            model_name='speciesmodel',
            name='disadvantages',
            field=models.ManyToManyField(null=True, to='character.DisadvantageModel'),
        ),
    ]
