# Generated by Django 3.1.2 on 2020-10-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20201006_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('trial', models.CharField(default='', max_length=255)),
                ('effect', models.CharField(default='', max_length=255)),
                ('casting_time', models.CharField(default='', max_length=255)),
                ('casting_cost', models.CharField(default='', max_length=255)),
                ('range', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('target_category', models.CharField(default='', max_length=255)),
                ('aspect', models.CharField(default='', max_length=255)),
                ('spread', models.CharField(default='', max_length=255)),
                ('leveling_cost', models.CharField(default='', max_length=1)),
                ('rule_book', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('trial', models.CharField(default='', max_length=255)),
                ('effect', models.CharField(default='', max_length=255)),
                ('casting_time', models.CharField(default='', max_length=255)),
                ('casting_cost', models.CharField(default='', max_length=255)),
                ('range', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('target_category', models.CharField(default='', max_length=255)),
                ('aspect', models.CharField(default='', max_length=255)),
                ('spread', models.CharField(default='', max_length=255)),
                ('leveling_cost', models.CharField(default='', max_length=1)),
                ('rule_book', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='spellextensionmodel',
            name='spell',
        ),
        migrations.DeleteModel(
            name='SpellModel',
        ),
    ]
