# Generated by Django 3.1.2 on 2020-10-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20201006_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantagemodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='disadvantagemodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
