# Generated by Django 3.1.2 on 2020-10-06 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20201006_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeremonyExtensionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('required_skill_value', models.IntegerField()),
                ('adventurer_point_cost', models.IntegerField()),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.ceremonymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChantExtensionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('required_skill_value', models.IntegerField()),
                ('adventurer_point_cost', models.IntegerField()),
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.chantmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SpellExtensionModel',
        ),
    ]
