# Generated by Django 3.1.2 on 2020-10-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_auto_20201006_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremonyextensionmodel',
            name='rule_book',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chantextensionmodel',
            name='rule_book',
            field=models.CharField(default='', max_length=255),
        ),
    ]
