# Generated by Django 3.1.2 on 2020-10-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_auto_20201006_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonymodel',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='ceremonymodel',
            name='leveling_cost',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chantmodel',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='chantmodel',
            name='leveling_cost',
            field=models.CharField(default='', max_length=255),
        ),
    ]
