# Generated by Django 3.1.2 on 2020-10-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20201006_0403'),
        ('character', '0015_auto_20201006_0358'),
    ]

    operations = [
    ]
