# Generated by Django 3.1.2 on 2020-10-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_merge_20201006_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonyextensionmodel',
            name='adventurer_point_cost',
        ),
        migrations.RemoveField(
            model_name='ceremonyextensionmodel',
            name='required_skill_value',
        ),
        migrations.RemoveField(
            model_name='ceremonyextensionmodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='chantextensionmodel',
            name='adventurer_point_cost',
        ),
        migrations.RemoveField(
            model_name='chantextensionmodel',
            name='required_skill_value',
        ),
        migrations.RemoveField(
            model_name='chantextensionmodel',
            name='rule_book',
        ),
        migrations.AlterField(
            model_name='ceremonyextensionmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ceremonymodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ceremonymodel',
            name='effect',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chantextensionmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chantmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chantmodel',
            name='effect',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='culturemodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
