# Generated by Django 3.1.2 on 2020-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_auto_20201006_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonymodel',
            name='aspect',
        ),
        migrations.RemoveField(
            model_name='chantmodel',
            name='aspect',
        ),
        migrations.AddField(
            model_name='ceremonyextensionmodel',
            name='rule_book',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chantextensionmodel',
            name='rule_book',
            field=models.CharField(default='', max_length=255),
        ),
    ]
