# Generated by Django 3.1.2 on 2020-10-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0018_auto_20201006_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremonyextensionmodel',
            name='rule_book_page',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='ceremonymodel',
            name='rule_book_page',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='chantextensionmodel',
            name='rule_book_page',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='chantmodel',
            name='rule_book_page',
            field=models.IntegerField(default=-1),
        ),
    ]
