# Generated by Django 3.1.2 on 2020-10-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0020_rulebookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebookmodel',
            name='cover',
            field=models.FileField(upload_to=''),
        ),
    ]
