# Generated by Django 3.1.2 on 2020-10-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_auto_20201006_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulebookmodel',
            name='cover',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
