# Generated by Django 3.1.2 on 2020-10-06 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0023_auto_20201006_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceremonyextensionmodel',
            name='rule_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel'),
        ),
        migrations.AlterField(
            model_name='ceremonymodel',
            name='rule_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel'),
        ),
        migrations.AlterField(
            model_name='chantextensionmodel',
            name='rule_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel'),
        ),
        migrations.AlterField(
            model_name='chantmodel',
            name='rule_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel'),
        ),
    ]
