# Generated by Django 3.1.2 on 2020-10-07 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_auto_20201006_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlessingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('effect', models.TextField()),
                ('range', models.CharField(default='', max_length=255)),
                ('duration', models.CharField(default='', max_length=255)),
                ('aspect', models.CharField(default='', max_length=255)),
                ('rule_book_page', models.IntegerField(default=-1)),
                ('rule_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel')),
            ],
        ),
    ]
