# Generated by Django 3.1.2 on 2020-10-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_blessingsmodel_target_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blessingsmodel',
            name='description',
        ),
    ]
