# Generated by Django 3.1.2 on 2020-10-08 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0027_remove_blessingsmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blessingsmodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='blessingsmodel',
            name='rule_book_page',
        ),
        migrations.RemoveField(
            model_name='ceremonyextensionmodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='ceremonyextensionmodel',
            name='rule_book_page',
        ),
        migrations.RemoveField(
            model_name='ceremonymodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='ceremonymodel',
            name='rule_book_page',
        ),
        migrations.RemoveField(
            model_name='chantextensionmodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='chantextensionmodel',
            name='rule_book_page',
        ),
        migrations.RemoveField(
            model_name='chantmodel',
            name='rule_book',
        ),
        migrations.RemoveField(
            model_name='chantmodel',
            name='rule_book_page',
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.rulebookmodel')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.pagemodel')),
            ],
        ),
        migrations.AddField(
            model_name='blessingsmodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel'),
        ),
        migrations.AddField(
            model_name='ceremonyextensionmodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel'),
        ),
        migrations.AddField(
            model_name='ceremonymodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel'),
        ),
        migrations.AddField(
            model_name='chantextensionmodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel'),
        ),
        migrations.AddField(
            model_name='chantmodel',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.sourcemodel'),
        ),
    ]
