# Generated by Django 3.1.2 on 2020-10-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_auto_20201008_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='GodAspectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='chantmodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ceremonymodel',
            name='spread',
        ),
        migrations.DeleteModel(
            name='ChantExtensionModel',
        ),
        migrations.DeleteModel(
            name='ChantModel',
        ),
        migrations.AddField(
            model_name='godaspectmodel',
            name='god',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.godmodel'),
        ),
        migrations.AddField(
            model_name='ceremonymodel',
            name='aspect',
            field=models.ManyToManyField(to='character.GodAspectModel'),
        ),
    ]
