# Generated by Django 3.1.2 on 2020-10-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0031_auto_20201013_0215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlessingsModel',
        ),
    ]
