# Generated by Django 3.1.2 on 2020-10-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0033_attributemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fst_attribute', to='character.attributemodel')),
                ('snd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snd_attribute', to='character.attributemodel')),
                ('trd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trd_attribute', to='character.attributemodel')),
            ],
        ),
    ]
