# Generated by Django 3.1.2 on 2020-10-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0035_auto_20201015_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ritualmodel',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.checkmodel'),
        ),
        migrations.AlterField(
            model_name='spellmodel',
            name='trial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.checkmodel'),
        ),
    ]
