# Generated by Django 3.1.2 on 2020-10-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0038_levelingcostmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ritualextensionmodel',
            name='ritual',
        ),
        migrations.RemoveField(
            model_name='ritualextensionmodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ritualmodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='ritualmodel',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='spellextensionmodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='spellextensionmodel',
            name='spell',
        ),
        migrations.RemoveField(
            model_name='spellmodel',
            name='source',
        ),
        migrations.RemoveField(
            model_name='spellmodel',
            name='trial',
        ),
        migrations.DeleteModel(
            name='CantripModel',
        ),
        migrations.DeleteModel(
            name='RitualExtensionModel',
        ),
        migrations.DeleteModel(
            name='RitualModel',
        ),
        migrations.DeleteModel(
            name='SpellExtensionModel',
        ),
        migrations.DeleteModel(
            name='SpellModel',
        ),
    ]
