# Generated by Django 3.1.2 on 2020-10-21 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0039_auto_20201019_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('applications', models.CharField(default='', max_length=255)),
                ('encumbrance', models.BooleanField(default=False)),
                ('quality', models.CharField(default='', max_length=255)),
                ('failed_check', models.CharField(default='', max_length=255)),
                ('critical_success', models.CharField(default='', max_length=255)),
                ('critical_failure', models.CharField(default='', max_length=255)),
                ('leveling_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.levelingcostmodel')),
                ('trial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.checkmodel')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.skilltypemodel')),
            ],
        ),
    ]
