# Generated by Django 3.1.2 on 2020-10-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0040_skillmodel_skilltypemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmodel',
            name='tools',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='encumbrance',
            field=models.CharField(default='', max_length=255),
        ),
    ]
